@baseURL = http://localhost:8080

###
GET {{baseURL}}/api/health

### @name createUser
POST {{baseURL}}/api/users
Content-Type: application/json

{
    "full_name": "Andrew",
    "age": 20,
    "phone_number": "+7183612389"
}

### Удаление пользователя по номеру
DELETE {{baseURL}}/api/users?phone=%2B7183612389

